// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(ApiDataContext))]
    partial class ApiDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Box", b =>
                {
                    b.Property<int>("BoxNo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("BoxNo");

                    b.ToTable("Box");
                });

            modelBuilder.Entity("API.Models.TemperatureSensor", b =>
                {
                    b.Property<int>("BoxNo");

                    b.Property<DateTime>("CtsNo");

                    b.Property<float>("TemperatureValue");

                    b.HasKey("BoxNo", "CtsNo");

                    b.HasIndex("BoxNo");

                    b.ToTable("Temperature");
                });

            modelBuilder.Entity("API.Models.TemperatureSensor", b =>
                {
                    b.HasOne("API.Models.Box", "Box")
                        .WithOne("TemperatureSensor")
                        .HasForeignKey("API.Models.TemperatureSensor", "BoxNo")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
