// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(ApiDataContext))]
    partial class ApiDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Box", b =>
                {
                    b.Property<int>("BoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("box_no")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("BoxId");

                    b.ToTable("Box");
                });

            modelBuilder.Entity("API.Models.TemperatureSensor", b =>
                {
                    b.Property<int>("BoxId")
                        .HasColumnName("box_no");

                    b.Property<DateTime>("Cts")
                        .HasColumnName("c_ts");

                    b.Property<float>("TemperatureValue")
                        .HasColumnName("temperature");

                    b.HasKey("BoxId", "Cts");

                    b.HasIndex("BoxId")
                        .IsUnique();

                    b.ToTable("Temperature");
                });

            modelBuilder.Entity("API.Models.TemperatureSensor", b =>
                {
                    b.HasOne("API.Models.Box", "Box")
                        .WithOne("TemperatureSensor")
                        .HasForeignKey("API.Models.TemperatureSensor", "BoxId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
